/*
   Saturday, August 06, 2005 10:03:16 PM
   User: 
   Server: (LOCAL)
   Database: blogdev
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.tblBlogEntries ADD
	enclosure nvarchar(255) NULL,
	filesize numeric(18, 0) NULL,
	mimetype nvarchar(255) NULL
GO
COMMIT
